
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 07 11:55:56 CST 2016
//----------------------------------------------------

package tiger.parse;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int DIVIDE = 18;
	public static final int FUNCTION = 42;
	public static final int GE = 24;
	public static final int LPAREN = 8;
	public static final int INT = 4;
	public static final int ARRAY = 28;
	public static final int FOR = 33;
	public static final int MINUS = 16;
	public static final int RPAREN = 9;
	public static final int SEMICOLON = 7;
	public static final int AND = 25;
	public static final int LT = 21;
	public static final int TYPE = 44;
	public static final int NIL = 41;
	public static final int IN = 37;
	public static final int OR = 26;
	public static final int COMMA = 5;
	public static final int PLUS = 15;
	public static final int ASSIGN = 27;
	public static final int IF = 29;
	public static final int DOT = 14;
	public static final int ID = 2;
	public static final int LE = 22;
	public static final int OF = 39;
	public static final int EOF = 0;
	public static final int error = 1;
	public static final int NEQ = 20;
	public static final int BREAK = 40;
	public static final int EQ = 19;
	public static final int LBRACK = 10;
	public static final int TIMES = 17;
	public static final int COLON = 6;
	public static final int LBRACE = 12;
	public static final int ELSE = 31;
	public static final int RBRACK = 11;
	public static final int TO = 34;
	public static final int WHILE = 32;
	public static final int LET = 36;
	public static final int THEN = 30;
	public static final int RBRACE = 13;
	public static final int END = 38;
	public static final int STRING = 3;
	public static final int GT = 23;
	public static final int VAR = 43;
	public static final int DO = 35;
}
